### ISSUE TITLE
TEST RESULTING IS 0

### ISSUE THREAD

**Issue by zzhangfan** [sdroh1027/DiffusionVID#2]
Thank you very much for open-sourcing the code! I trained RDN-BASE using the "vid_R_101_C4_RDN_base_1x.yaml"  file you provided in the codebase. However, when I performed the inference, I found that the outputs were all zeros. Is there something that needs to be changed in the code?

**Comment by sdroh1027** [comment]
This was a normalization issue: We found an issue where certain methods were not normalizing properly in the test phase (including RDN, DFF, and FGFA). We've fixed it by committing the corrected code. Thanks for the report!

**Comment by zzhangfan** [comment]
Thank you very much for your reply, I will download the latest code base for testing! However, I am getting a new error when using the "vid_R_101_C4_MEGA_1x.yaml " file for single GPU training of MEGA:   an index out of bounds error at line 1143 of  roi_box_feature_extractors.py (feats_ref = self.global_cache[0]["feats"]). So is it possible here to just replace MEGAFeatureExtractor.py in mega.pytorch with the  MEGAFeatureExtractor.py you are using?

**Comment by sdroh1027** [comment]
I don't think I understood your question. Training mega works fine in the current version of the code.  I'm guessing that the "index out of bounds error" at line 1143 is an error that occurs when the global features are not updated to self.global_cache. Did you modify anything in your code or config that is different from the original?
