### ISSUE TITLE
Where can I download the ImageNet VID dataset?

### ISSUE THREAD

**Issue by lively2018** [sdroh1027/DiffusionVID#5]
Hello,

ILSVRC2017 object detection from video link at imagenet-org is broken. ILSVRC2015 also doesn't work. Where can I get the object detection from video? Or could you recommend any other dataset for object detection from video?

Thanks.

**Comment by sdroh1027** [comment]
I updated [google drive link](https://drive.google.com/file/d/13iD3maoxiUEqeZmonODm3B03NCGCPJFh/view?usp=drive_link)  and updated readme file.
